yolact_ros2_3d_node:
  ros__parameters:
    yolact_ros_topic: /yolact_ros2/detections
    output_bbx3d_topic: /yolact_ros2_3d/bounding_boxes_3d
    point_cloud_topic: /camera/pointcloud
    working_frame: camera_link
    maximum_detection_threshold: 0.2
    minimum_probability: 0.4
    interested_classes: ["person", "dog", "tv", "keyboard"]
    eroding_factors: ["2", "1", "3", "1"]
    thinning_factors: ["90", "20", "80", "80"]
    debug: true
